create table BOARD(
   BOARD_NUM NUMBER(5) PRIMARY KEY,
   BOARD_NAME VARCHAR(100) NOT NULL,
   BOARD_CONTENT VARCHAR(100) NOT NULL,
   BOARD_WRITER VARCHAR(100) NOT NULL,
   BOARD_DATE DATE,
   BOARD_VIWCNT NUMBER(5) NOT NULL,
   BOARD_LIKE NUMBER(5) NOT NULL,
   BOARD_DISLIKE NUMBER(5) NOT NULL,
   BOARD_BLAME NUMBER(5) NOT NULL,
   BOARD_WRITE_ID VARCHAR(50) NOT NULL
);